name: BuildImage

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=time::$(date +'%Y%m%d%H')"
        echo "::set-output name=tag::${GITHUB_REF#refs/*/}"

    - name: Build
      run: go mod tidy && go build .

    - name: Test
      run: go build . && go test -v .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: ccr.ccs.tencentyun.com/serverlessv1/http_bench:http_bench-${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.time }}