name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build for multiple platforms
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Build for Linux AMD64
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/http_bench-linux-amd64 .
        
        # Build for Linux ARM64
        GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o dist/http_bench-linux-arm64 .
        
        # Build for macOS AMD64
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o dist/http_bench-darwin-amd64 .
        
        # Build for macOS ARM64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o dist/http_bench-darwin-arm64 .
        
        # Build for Windows AMD64
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o dist/http_bench-windows-amd64.exe .
        
        # Build for Windows ARM64
        GOOS=windows GOARCH=arm64 go build -ldflags "-s -w" -o dist/http_bench-windows-arm64.exe .

    - name: Create archives
      run: |
        cd dist
        
        # Create tar.gz for Linux and macOS
        tar -czf http_bench-linux-amd64.tar.gz http_bench-linux-amd64
        tar -czf http_bench-linux-arm64.tar.gz http_bench-linux-arm64
        tar -czf http_bench-darwin-amd64.tar.gz http_bench-darwin-amd64
        tar -czf http_bench-darwin-arm64.tar.gz http_bench-darwin-arm64
        
        # Create zip for Windows
        zip http_bench-windows-amd64.zip http_bench-windows-amd64.exe
        zip http_bench-windows-arm64.zip http_bench-windows-arm64.exe

    - name: Generate checksums
      run: |
        cd dist
        sha256sum *.tar.gz *.zip > checksums.txt

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          ## Changes in ${{ steps.get_version.outputs.VERSION }}
          
          ### Downloads
          
          #### Linux
          - [http_bench-linux-amd64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/http_bench-linux-amd64.tar.gz) - Linux x86_64
          - [http_bench-linux-arm64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/http_bench-linux-arm64.tar.gz) - Linux ARM64
          
          #### macOS
          - [http_bench-darwin-amd64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/http_bench-darwin-amd64.tar.gz) - macOS Intel
          - [http_bench-darwin-arm64.tar.gz](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/http_bench-darwin-arm64.tar.gz) - macOS Apple Silicon
          
          #### Windows
          - [http_bench-windows-amd64.zip](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/http_bench-windows-amd64.zip) - Windows x86_64
          - [http_bench-windows-arm64.zip](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/http_bench-windows-arm64.zip) - Windows ARM64
          
          #### Verification
          - [checksums.txt](https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/checksums.txt) - SHA256 checksums

    - name: Upload Linux AMD64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/http_bench-linux-amd64.tar.gz
        asset_name: http_bench-linux-amd64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Linux ARM64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/http_bench-linux-arm64.tar.gz
        asset_name: http_bench-linux-arm64.tar.gz
        asset_content_type: application/gzip

    - name: Upload macOS AMD64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/http_bench-darwin-amd64.tar.gz
        asset_name: http_bench-darwin-amd64.tar.gz
        asset_content_type: application/gzip

    - name: Upload macOS ARM64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/http_bench-darwin-arm64.tar.gz
        asset_name: http_bench-darwin-arm64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Windows AMD64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/http_bench-windows-amd64.zip
        asset_name: http_bench-windows-amd64.zip
        asset_content_type: application/zip

    - name: Upload Windows ARM64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/http_bench-windows-arm64.zip
        asset_name: http_bench-windows-arm64.zip
        asset_content_type: application/zip

    - name: Upload Checksums
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain